export const MAIN_CONTENT_DIV = document.querySelector('.main-content')
export const HEADER = document.querySelector('header')
export const SECTION = document.querySelector('section')
export const DISCOVER_PAGE = document.querySelector('.discover-page')
export const HOME_PAGE = document.querySelector('.homepage')
export const TOP_MOVIES_PAGE = document.querySelector('top_movies')

export const DISCOVER_FILTERS = document.createElement('div')
export const DIV_FOR_INPUT = document.createElement('div')
export const UPPER_HEADING = document.createElement('h1')
export const LOWER_HEADING= document.createElement('h1')
export const SEARCH_BUTTON = document.createElement('button')
export const SEARCH_INPUT = document.createElement('input')
